# -*- coding: utf-8 -*-
"""How to Use Webcam

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYpEc_EqZyMMArHU4qX4EZ5gPkDctDsr
"""

from IPython.display import display, Javascript, Image
from google.colab.output import eval_js
from base64 import b64decode, b64encode
import numpy as np
import PIL
import io
import cv2
import html
import time

def js_rto_img(js_reply):
  """
  containing
  """

  img_bytes = b64decode(js_reply.split(',')[1])
  img = PIL.Image.open(io.BytesIO(img_bytes))
  return img

def box_to_bytes(box_array):
  bbox_pil = PIL.Image.fromarray(box_array, 'RGBA')

js = """
  async function takePhoto(quality) {
    const vid = docment.createElement('video');
    const cap = document.createElement('canvas');
    cap.textContent = 'capturing';

    document.body.appendChild(vid);
    document.body.appendChild(cap);

    const stream = await navigator.mediaDevices.getUserMedia({video: true\});
    vid.srcObject = stream;
    await vid.play();

    await.new Promis((resolve) => cap.onclick = resolve);

    const canvas = document.createElement('canvas);
    canvas.width = vid.videoWidth;
    canvas.height = vid.videoHeight;
    canvas.getContext('2d').drawImage(vid, 0, 0);

    stream.getTraks().forEach(track => track.stop());
    vid.remove();
    cap.remove();

    return canvas.toDataURL('image/jpeg', quality);
  }
    """

def takePhoto(img_name='cap_img', img_type='.jpg'):
  if img_type.lower() not in ['.jpg', '.jpg', 'png']:
    raise ValueError("Invalid", "jpg", "jpg", ".png")

    display(Javascript(js))
    data = eval_js('takePhoto()')
    img_data = base64.b64decode(data.split(',')[1])
    img = PTL.Image.open(io.BytesIO(img_data))

    file_name = f"Img Saved: {file_name}"
    img.save(filename)
    return Image

img = takePhoto()
display(img)